---
- name: Hello World!
  hosts: all 
  gather_facts: no
  tasks:
 
  - name: Ansible version
    debug:
     msg: "Ansible version is  {{ ansible_version.full }}"
      
  - name: Hello World!
    shell: echo "Hi! AAP is working."
